### ISSUE TITLE
No win screen

### ISSUE THREAD

**Issue by ArchieHill** [ollyrowe/whittle#93]
I got a solution where all tiles were green but there was no win screen. How am I supposed to feel good when nothing tells me I've won. I want win screen with animated celebrations going off to make me feel good. Monkey sad otherwise.

**Comment by ArchieHill** [comment]
So I just found out how to get win screen, it's not clear enough that all the words need to be joined together instead of just highlighted green, have some pop up or something that indicates all the words to be joined together or something when all the letters are green

**Comment by emilielake** [comment]
@ArchieHill There's a how to play pop up that automatically displays when you play the game for the first time that specifies 'All words must be connected to win the game' - Not our fault if you can't read I'm afraid.

**Comment by ArchieHill** [comment]
No, it's not worded clearly enough if I missed it when first reading it. Either make the words more clear or put a pop up that appears when all the tiles are green but the words aren't joined together

**Comment by emilielake** [comment]
Could potentially have a message displayed in the tile rack if all tiles are on placed on the board but do not meet the requirements to win the game tbf? This message could either tell the user that not all their tiles are connected or that at least one of their words is invalid - or both.

**Comment by ollyrowe** [comment]
The wording within the how to play modal is plenty clear enough, but I suppose _some people_ might not have the attention span to read it. As @emilielake said, I think the best solution here would be to add a message which is displayed in this scenario. We'll get something added.

**Comment by ollyrowe** [comment]
Closing as this is to be addressed as part of #127
