### ISSUE TITLE
New game title

### ISSUE THREAD

**Issue by ArchieHill** [ollyrowe/whittle#94]
So the thing is called whittle, this is not a very good name. I propose woffle instead, it's a play on words from waffle and waffles are yummy with bananas which your game was inspired by (bananagrams). Maybe this can be expanded more to somehow included maple syrup for extra yumminess.

**Comment by emilielake** [comment]
@ArchieHill Waffle as a word game already exists, please see https://wafflegame.net/. Your proposed change in spelling is not unique enough

**Comment by ArchieHill** [comment]
I proposed woffle, not waffle

**Comment by ollyrowe** [comment]
Booooo
