### ISSUE TITLE
Uncentered

### ISSUE THREAD

**Issue by ArchieHill** [ollyrowe/whittle#95]
I played the game for a bit and had a constant feeling growing on me that something was off. So I got out my ruler and measured the dimensions, consulted with the demon Backrutdul and did some mediation. I was shocked to find that the grid is 0.247 pixels off the centre of the screen. This is outrages and must be fixed immediately not doing so would be a crime against humanity.

**Comment by emilielake** [comment]
Go away

**Comment by ArchieHill** [comment]
No

**Comment by ollyrowe** [comment]
Giving you the benefit of the doubt that there's at least a hint of sincerity within this issue... we're aware that the board doesn't fit on very small phone displays and we'll be looking into a fix for this.

**Comment by ArchieHill** [comment]
Yeah, there's no sincerity. I thought that would be obvious by the fact I consulted a demon and said it was offset by less then a pixel.... I also played it on a computer instead of a phone. But by all means turn this into a problem of not fitting nicely on small screens
