### ISSUE TITLE
Shortcut to remove a tile from the grid

### ISSUE THREAD

**Issue by ArchieHill** [ollyrowe/whittle#98]
Could there be a shortcut to remove a tile from the grid. For instance you could right click the tile and it would jump back to the pool of tiles outside the grid

**Comment by ollyrowe** [comment]
Sure, sounds sensible. I suppose we'd want to make this as intuitive as possible. In general, if someone right clicks then they'd probably expect to see a context menu. Perhaps a double click might work a bit better? This would also allow for mobile users to use the shortcut too :)

**Comment by ArchieHill** [comment]
Sure that would work, a right click was only an example of what it could be
